name: Create a new Coineda Release

on:
  push:
    branches: ['main']

  workflow_dispatch:

jobs:
  create_release:
    runs-on: ubuntu-latest
    if: "${{ !contains(github.event.head_commit.message, 'release-please--branches--main') }}"
    steps:
      - name: ⬇️ Checkout repository
        uses: actions/checkout@v4

      - name: 🫡 Setup node
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: npm

      - name: 🧘‍♀️ Download dependencies
        run: npm ci

      - name: 🎳 Run tests
        run: npx vitest run

      - name: 🚀 release-please-action
        uses: google-github-actions/release-please-action@v3
        with:
          release-type: node
          versioning-strategy: always-bump-patch
