name: Create a new Coineda Release

on:
  push:
    branches: ['main']
  pull_request:
    branches: ['main']

  workflow_dispatch:

jobs:
  create_release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: ⏰ Wait for tests to succeed
        uses: lewagon/wait-on-check-action@v1.2.0
        with:
          ref: ${{ github.ref }}
          running-workflow-name: 'Run Tests'
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          wait-interval: 20

      - name: release-please-action
        uses: google-github-actions/release-please-action@v3
        with:
          release-type: node
          versioning-strategy: always-bump-patch
